// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCva2jjveu4Briznr0eYz4mxkoayXJzZfM',
    appId: '1:299048422905:web:7b4ab81e333ee47c368128',
    messagingSenderId: '299048422905',
    projectId: 'aimathtest-kids-3ca24',
    authDomain: 'aimathtest-kids-3ca24.firebaseapp.com',
    storageBucket: 'aimathtest-kids-3ca24.firebasestorage.app',
    measurementId: 'G-2EXKPCJJ8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_kz5Ewci6f-7iolTTGuGddMkHUhITOBo',
    appId: '1:299048422905:android:cea4b9bfa6581159368128',
    messagingSenderId: '299048422905',
    projectId: 'aimathtest-kids-3ca24',
    storageBucket: 'aimathtest-kids-3ca24.firebasestorage.app',
  );
}
